#!/bin/sh
# One-time root bootstrap for the builder plane (ADR-0023,
# docs/design/builder-plane.md). Run ON the app host:
#
#   sudo sh ~/bespoke/repo/deploy/bootstrap-builder.sh <platform-user> <repo-url>
#
# e.g.  sudo sh deploy/bootstrap-builder.sh bjk https://github.com/bketelsen/bespoke
#
# Everything after this script is unprivileged: the platform user's deploy
# watcher and the builder user's runner are ordinary systemd --user units.
set -eu

PLATFORM_USER="${1:?usage: bootstrap-builder.sh <platform-user> <repo-url>}"
REPO_URL="${2:?usage: bootstrap-builder.sh <platform-user> <repo-url>}"
SPOOL=/var/lib/bespoke/spool
BIN=/var/lib/bespoke/bin

echo "==> group + builder user"
getent group bespoke >/dev/null || groupadd --system bespoke
id builder >/dev/null 2>&1 || useradd --create-home --shell /bin/bash builder
usermod -aG bespoke "$PLATFORM_USER"
usermod -aG bespoke builder

echo "==> spool + shared bin (setgid so both sides share group ownership)"
mkdir -p "$SPOOL/build" "$SPOOL/deploy" "$SPOOL/runs" "$SPOOL/archive" "$BIN"
chgrp -R bespoke /var/lib/bespoke
chmod 2770 "$SPOOL" "$SPOOL/build" "$SPOOL/deploy" "$SPOOL/runs" "$SPOOL/archive"
chmod 2775 "$BIN"

echo "==> copilot CLI for the builder user (self-contained binary)"
if [ -x "/home/$PLATFORM_USER/.local/bin/copilot" ] && [ ! -x "$BIN/copilot" ]; then
	cp "/home/$PLATFORM_USER/.local/bin/copilot" "$BIN/copilot"
	chgrp bespoke "$BIN/copilot" && chmod 755 "$BIN/copilot"
fi

echo "==> builder runner units (builder's own user-systemd)"
loginctl enable-linger builder
RUNNER_UNITS=/home/builder/.config/systemd/user
mkdir -p "$RUNNER_UNITS"
cat > "$RUNNER_UNITS/bespoke-buildrunner.path" <<EOF
# GENERATED by bootstrap-builder.sh — do not edit
[Unit]
Description=Bespoke build spool watcher (ADR-0023)

[Path]
DirectoryNotEmpty=$SPOOL/build

[Install]
WantedBy=default.target
EOF
cat > "$RUNNER_UNITS/bespoke-buildrunner.service" <<EOF
# GENERATED by bootstrap-builder.sh — do not edit
[Unit]
Description=Bespoke build runner: agentic app builds (ADR-0023)

[Service]
Type=oneshot
Environment=BESPOKE_SPOOL=$SPOOL
Environment=BESPOKE_REPO_URL=$REPO_URL
Environment=PATH=$BIN:/home/linuxbrew/.linuxbrew/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=$BIN/builder-runner
TimeoutStartSec=3h
EOF
chown -R builder:builder /home/builder/.config

echo "==> done. Remaining manual steps:"
echo "  1. As $PLATFORM_USER: clone the repo to ~/bespoke/repo, create"
echo "     deploy/deploy.env in it (SELFIE_SSH can point at this host), and"
echo "     make sure 'ssh \$SELFIE_SSH true' and 'ssh \$EDGE_SSH true' work"
echo "     non-interactively from here."
echo "  2. Authenticate the builder user's Copilot CLI (interactive, once):"
echo "       sudo machinectl shell builder@ /usr/bin/env bash -lc copilot"
echo "     (or: sudo -iu builder, then run copilot and sign in)"
echo "  3. Deploy from the dev machine — 'just deploy' now ships bespoke +"
echo "     builder-runner into $BIN and enables the deploy watcher."
echo "  4. Enable the runner as builder:"
echo "       sudo -iu builder systemctl --user enable --now bespoke-buildrunner.path"
